name: utility
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dependencies:
  logger: ^1.4.0

  flutter_lints: ^2.0.0
