name: dependencies
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  app_settings: ^5.1.1
  bloc: ^8.1.2
  collection: ^1.17.2
  equatable: ^2.0.5
  firebase_core: ^2.17.0
  firebase_remote_config: ^4.2.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_platform_widgets: ^3.3.5
  formz: ^0.6.1
  location: ^5.0.3
  percent_indicator: ^4.2.3
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.1
  table_desk: ^0.0.1
  uuid: ^4.1.0
