// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvZxBLHAFNKSc7DmH0QVyAFo9WF2Ge_TE',
    appId: '1:485214740363:web:e318fdfd89ee718b54198e',
    messagingSenderId: '485214740363',
    projectId: 'flutter-caddyapp',
    authDomain: 'flutter-caddyapp.firebaseapp.com',
    storageBucket: 'flutter-caddyapp.appspot.com',
    measurementId: 'G-J28MZZXJQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBipuVwdVVlJxoE3jMKsfCIc-gn6UrbbnU',
    appId: '1:485214740363:android:5d184ea8f9f37ff954198e',
    messagingSenderId: '485214740363',
    projectId: 'flutter-caddyapp',
    storageBucket: 'flutter-caddyapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2x4jQWIMgg2aygOaVg_IFvjwpG9Nh8iY',
    appId: '1:485214740363:ios:a799ace75220595154198e',
    messagingSenderId: '485214740363',
    projectId: 'flutter-caddyapp',
    storageBucket: 'flutter-caddyapp.appspot.com',
    iosBundleId: 'com.example.flutterCaddyApp',
  );
}
