name: core

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  blocs:
    path: ../blocs

  dependencies:
    path: ../dependencies

  models:
    path: ../models

  repository:
    path: ../repository

  pages:
    path: ../pages

  utility:
    path: ../utility
  flutter_native_splash: ^2.3.3
  permission_handler: ^11.0.1

flutter:
  uses-material-design: true

  assets:
    - ../../assets/images/
